workload: 'node-density'
uuid: 'a9ddd61b-d12e-4922-86a2-ea17354d80hh'
es_server: ''
es_index: ''
qps: 20
burst: 20
log_level: 'info'
pods_per_node: 80
timeout: '25m'
pod_ready_threshold: '20s'
kubeconfig: |
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CR...
      server: https://api.dummycluster.openshift.com:6443
    name: api-dummycluster-openshift-com:6443
